In [ ]:
# --- Interactive Environment ---
%matplotlib inline

# --- Standard Library ---
import os
import re
import glob
import json
import pickle
from pathlib import Path
from datetime import datetime
from typing import Sequence, Optional, Tuple, Dict, Union
from dataclasses import dataclass
from itertools import combinations

# --- Third-Party Libraries ---
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib import colormaps
from matplotlib.backends.backend_pdf import PdfPages
from matplotlib.colors import TwoSlopeNorm
from matplotlib.lines import Line2D
from scipy.stats import linregress, mannwhitneyu, spearmanr, pearsonr, wilcoxon, binomtest, norm, fisher_exact
import statsmodels.api as sm
from statsmodels.stats.multitest import multipletests
from sklearn.preprocessing import StandardScaler

In [1]:
import pandas as pd

tongue_kins = pd.read_parquet(
    "/root/capsule/scratch/session_analysis_mlk/behavior_716325_2024-05-31_10-31-14/intermediate_data/tongue_kins.parquet"
)

print(tongue_kins.shape)
print(tongue_kins.dtypes)
tongue_kins.head()

(2689718, 13)
time               float64
x                  float64
y                  float64
v                  float64
xv                 float64
yv                 float64
time_raw           float64
confidence         float64
movement_id          Int64
time_in_session    float64
trial              float64
lick                  bool
lick_index         float64
dtype: object

,time,x,y,v,xv,yv,time_raw,confidence,movement_id,time_in_session,trial,lick,lick_index
0,0.000000,NaN,NaN,NaN,NaN,NaN,3.892922e+06,0.000276,<NA>,-48.577536,NaN,False,NaN
1,0.001952,NaN,NaN,NaN,NaN,NaN,3.892922e+06,0.000224,<NA>,-48.575584,NaN,False,NaN
2,0.003968,NaN,NaN,NaN,NaN,NaN,3.892922e+06,0.000240,<NA>,-48.573568,NaN,False,NaN
3,0.005952,NaN,NaN,NaN,NaN,NaN,3.892922e+06,0.000187,<NA>,-48.571584,NaN,False,NaN
4,0.007968,NaN,NaN,NaN,NaN,NaN,3.892922e+06,0.000213,<NA>,-48.569568,NaN,False,NaN

In [4]:
tongue_kins[tongue_kins['movement_id']==13].head(10)

,time,x,y,v,xv,yv,time_raw,confidence,movement_id,time_in_session,trial,lick,lick_index
14408,28.815872,344.912091,354.238199,2047.008717,1406.235034,-1487.530745,3.892951e+06,0.983531,13,-19.761664,NaN,False,NaN
14409,28.817856,347.347824,351.699782,1432.871246,1027.303765,-998.882866,3.892951e+06,0.991306,13,-19.759680,NaN,False,NaN
14410,28.819872,349.021306,350.242668,829.086569,698.715523,-446.297162,3.892951e+06,0.987833,13,-19.757664,NaN,False,NaN
14411,28.821856,350.142686,349.914593,517.276389,508.151943,96.728825,3.892951e+06,0.997045,13,-19.755680,NaN,False,NaN
14412,28.823872,351.053914,350.629584,737.359567,484.905844,555.486682,3.892951e+06,0.996731,13,-19.753664,NaN,False,NaN
14413,28.825856,352.082309,352.136540,1029.052165,598.077079,837.408004,3.892951e+06,0.989180,13,-19.751680,NaN,False,NaN
14414,28.827872,353.446222,353.979215,1177.438926,786.485497,876.243681,3.892951e+06,0.991082,13,-19.749664,NaN,False,NaN
14415,28.829856,355.228251,355.641514,1211.324697,983.369160,707.313662,3.892951e+06,0.994029,13,-19.747680,NaN,False,NaN
14416,28.831872,357.379698,356.808470,1211.222046,1123.261927,453.146210,3.892951e+06,0.985912,13,-19.745664,NaN,False,NaN
14417,28.833856,359.721299,357.454099,1169.268197,1147.679047,223.653575,3.892951e+06,0.997693,13,-19.743680,NaN,False,NaN